pivotjs:
  css:
    - ./lib/css/bootstrap.min.css
    - ./lib/css/subnav.css
    - ./lib/css/pivot.css
  jshead:
    - ./lib/js/jquery.min.js
    - ./lib/js/subnav.js
    - ./lib/js/accounting.min.js
    - ./lib/js/jquery.dataTables.min.js
    - ./lib/js/dataTables.bootstrap.js
    - ./lib/js/pivot.js
    - ./lib/js/jquery_pivot.js
    - ./lib/js/jsonfn.js
